INITIAL_PRODUCTS = [
    {
        'id': 'prod-dell-72891',
        'productId': 'RP-DL-72891',
        'brand': 'Dell',
        'model': 'Inspiron 15 5000',
        'category': 'Laptop',
        'serialNumber': 'CN-0K752D-72891-49A-0382',
        'purchaseDate': '2024-03-15',
        'manufactureDate': '2024-01-20',
        'condition': 'GOOD',
        'warranty': 'Expired (1 Year Manufacturer)',
        'repairabilityScore': 8.5,
        'estimatedResaleMin': 8500,
        'estimatedResaleMax': 11000,
        'lifecycleStatus': 'ACTIVE',
        'ownerId': 'user-avi',
        'ownerName': 'Avi Sharma',
        'specs': {
            'processor': 'Intel Core i5-1135G7 @ 2.40GHz',
            'ram': '16GB DDR4 3200MHz',
            'storage': '512GB NVMe PCIe M.2 SSD',
            'batteryHealth': '84% (46,200 mWh remaining)',
            'display': '15.6" FHD (1920x1080) Anti-glare',
            'color': 'Platinum Silver'
        },
        'repairCount': 2,
        'verifiedRepairsCount': 2,
        'invoiceName': 'Dell_Tax_Invoice_2025.pdf'
    },
    {
        'id': 'prod-iphone-93104',
        'productId': 'RP-AP-93104',
        'brand': 'Apple',
        'model': 'iPhone 13 Pro',
        'category': 'Smartphone',
        'serialNumber': 'F17FK9V00N73',
        'purchaseDate': '2023-09-20',
        'manufactureDate': '2023-08-10',
        'condition': 'EXCELLENT',
        'warranty': 'Expired',
        'repairabilityScore': 6.8,
        'estimatedResaleMin': 38000,
        'estimatedResaleMax': 42000,
        'lifecycleStatus': 'ACTIVE',
        'ownerId': 'user-avi',
        'ownerName': 'Avi Sharma',
        'specs': {
            'processor': 'A15 Bionic 6-core',
            'ram': '6GB',
            'storage': '256GB',
            'batteryHealth': '89% Original OEM',
            'display': '6.1" Super Retina XDR ProMotion 120Hz',
            'color': 'Sierra Blue'
        },
        'repairCount': 1,
        'verifiedRepairsCount': 1
    },
    {
        'id': 'prod-samsung-58219',
        'productId': 'RP-SM-58219',
        'brand': 'Samsung',
        'model': 'Galaxy S23 Ultra',
        'category': 'Smartphone',
        'serialNumber': 'R58W10XYZ82',
        'purchaseDate': '2023-05-12',
        'manufactureDate': '2023-03-01',
        'condition': 'GOOD',
        'warranty': 'Expired',
        'repairabilityScore': 7.2,
        'estimatedResaleMin': 45000,
        'estimatedResaleMax': 50000,
        'lifecycleStatus': 'RESOLD',
        'ownerId': 'user-buyer-44',
        'ownerName': 'Priya Mehta',
        'specs': {
            'processor': 'Snapdragon 8 Gen 2 for Galaxy',
            'ram': '12GB',
            'storage': '256GB',
            'batteryHealth': '91%',
            'display': '6.8" Dynamic AMOLED 2X 120Hz',
            'color': 'Phantom Black'
        },
        'repairCount': 1,
        'verifiedRepairsCount': 1
    }
]

INITIAL_LIFECYCLE_EVENTS = [
    {
        'id': 'event-dl-1',
        'productId': 'RP-DL-72891',
        'eventType': 'MANUFACTURED',
        'title': 'Manufactured & Quality Checked',
        'description': 'Dell Chengdu Facility. Passed OEM mechanical, thermal and battery health inspection.',
        'timestamp': '2024-01-20T08:30:00Z',
        'verified': True,
        'verificationLevel': 'DOCUMENT_VERIFIED',
        'actorName': 'Dell Global Logistics',
        'actorRole': 'ADMIN'
    },
    {
        'id': 'event-dl-2',
        'productId': 'RP-DL-72891',
        'eventType': 'REGISTERED',
        'title': 'Product Passport Registered',
        'description': 'Product registered by initial owner with verifiable serial number and proof of purchase.',
        'timestamp': '2024-03-15T10:00:00Z',
        'verified': True,
        'verificationLevel': 'USER_REPORTED',
        'actorName': 'Avi Sharma',
        'actorRole': 'OWNER'
    },
    {
        'id': 'event-dl-3',
        'productId': 'RP-DL-72891',
        'eventType': 'REPAIR',
        'title': 'Battery Replaced',
        'description': 'Replaced degraded 42Wh pack with authentic Dell OEM 3-Cell 54Wh Li-Ion battery. Calibrated charging cycle.',
        'timestamp': '2025-04-18T14:22:00Z',
        'verified': True,
        'verificationLevel': 'REPAIRER_VERIFIED',
        'actorName': 'TechFix Solutions',
        'actorRole': 'REPAIRER',
        'cost': 3200,
        'partsReplaced': ['Dell OEM 54Wh Battery (G91J0)'],
        'documentName': 'TechFix_Invoice_INV-88219.pdf'
    },
    {
        'id': 'event-dl-4',
        'productId': 'RP-DL-72891',
        'eventType': 'MAINTAINED',
        'title': 'Thermal Cleaning & Re-Paste',
        'description': 'Full heatsink ultrasonic cleaning, dust purge, and Arctic MX-6 thermal compound re-application.',
        'timestamp': '2026-02-12T11:45:00Z',
        'verified': True,
        'verificationLevel': 'DOCUMENT_VERIFIED',
        'actorName': 'TechFix Solutions',
        'actorRole': 'REPAIRER',
        'cost': 1200,
        'partsReplaced': ['Thermal Interface Material (Arctic MX-6)'],
        'documentName': 'Service_WorkOrder_WO-9912.pdf'
    }
]

def get_product(product_id):
    for p in INITIAL_PRODUCTS:
        if p['productId'].upper() == product_id.upper() or p['id'] == product_id:
            return p
    return None

def get_product_events(product_id):
    events = [e for e in INITIAL_LIFECYCLE_EVENTS if e['productId'].upper() == product_id.upper()]
    events.sort(key=lambda x: x['timestamp'], reverse=True)
    return events

INITIAL_REPAIRERS = [
    {
        'id': 'rep-techfix',
        'userId': 'user-repairer',
        'name': 'TechFix Solutions',
        'ownerName': 'Marcus Vance',
        'specialty': 'Laptop & Computer Specialist',
        'category': ['Laptop', 'Desktop', 'Tablet'],
        'distanceKm': 1.5,
        'verified': True,
        'verificationStatus': 'VERIFIED',
        'rating': 4.9,
        'reviewCount': 326,
        'completedRepairs': 342,
        'location': 'Hazratganj Tech Hub, Lucknow',
        'address': 'Hazratganj Tech Hub, 4th Floor, Suite 402',
        'city': 'Lucknow',
        'state': 'Uttar Pradesh',
        'pincode': '226001',
        'experienceYears': 6,
        'openingHours': 'Mon–Sat: 10:00 AM – 8:00 PM | Sun: Closed',
        'availability': 'OPEN',
        'description': 'Specialized in laptop diagnostics, precision thermal repasting, BGA reballing, and component replacement with cryptographic ReTrace passport minting.',
        'services': ['Laptop Repair', 'Battery Replacement', 'Thermal Cleaning', 'Screen Replacement', 'Motherboard Diagnostics'],
        'specializations': ['Dell', 'HP', 'Lenovo', 'Apple'],
        'issueTypes': ['Screen Repair', 'Battery Replacement', 'Charging Problems', 'Overheating', 'Motherboard Repair', 'Hardware Problems'],
        'hourlyRate': 850,
        'avatar': 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
        'responseTime': '< 1 hour',
        'phone': '+91 98450 12891',
        'email': 'marcus@techfix.com',
        'certifications': ['IPC-A-610 Master Technician', 'Dell Certified System Expert', 'Apple Independent Repair Provider']
    },
    {
        'id': 'rep-devicecare',
        'name': 'DeviceCare Studio',
        'ownerName': 'Ananya Sharma',
        'specialty': 'Smartphone + Laptop Specialist',
        'category': ['Smartphone', 'Laptop', 'Tablet'],
        'distanceKm': 2.4,
        'verified': True,
        'verificationStatus': 'VERIFIED',
        'rating': 4.8,
        'reviewCount': 210,
        'completedRepairs': 238,
        'location': 'Koramangala 5th Block, Bengaluru',
        'address': '80ft Road, Near Sony World Signal',
        'city': 'Bengaluru',
        'state': 'Karnataka',
        'pincode': '560095',
        'experienceYears': 5,
        'openingHours': 'Mon–Sat: 09:30 AM – 08:30 PM | Sun: 11:00 AM – 04:00 PM',
        'availability': 'OPEN',
        'description': 'Certified multi-brand micro-electronics restoration lab. Specialists in OLED optical lamination and precision battery management systems.',
        'services': ['Screen Replacement', 'Battery Replacement', 'Charging Problems', 'Micro-soldering', 'Diagnostics'],
        'specializations': ['Apple', 'Samsung', 'OnePlus', 'Dell'],
        'hourlyRate': 950,
        'avatar': 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=80',
        'responseTime': '< 2 hours',
        'phone': '+91 98860 33412',
        'email': 'contact@devicecare.in'
    },
    {
        'id': 'rep-laptoplab',
        'name': 'LaptopLab Pro',
        'ownerName': 'Vikramaditya Roy',
        'specialty': 'Laptop Specialist & Thermal Systems',
        'category': ['Laptop', 'Desktop'],
        'distanceKm': 3.8,
        'verified': True,
        'verificationStatus': 'VERIFIED',
        'rating': 4.7,
        'reviewCount': 150,
        'completedRepairs': 174,
        'location': 'Indiranagar 100ft Rd, Bengaluru',
        'address': '100ft Road, Above Blue Tokai Coffee',
        'city': 'Bengaluru',
        'state': 'Karnataka',
        'pincode': '560038',
        'experienceYears': 8,
        'openingHours': 'Mon–Sat: 10:00 AM – 07:30 PM | Sun: Closed',
        'availability': 'OPEN',
        'description': 'Dedicated enterprise and workstation maintenance depot. Ultrasonic board bath, heatsink repasting, and structural hinge reconstruction.',
        'services': ['Thermal Cleaning', 'Screen Replacement', 'Keyboard Replacement', 'Motherboard Diagnostics'],
        'specializations': ['Lenovo', 'HP', 'Dell', 'Asus'],
        'hourlyRate': 800,
        'avatar': 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=500&auto=format&fit=crop&q=80',
        'responseTime': '< 3 hours',
        'phone': '+91 99011 44819',
        'email': 'roy@laptoplab.co'
    },
    {
        'id': 'rep-apex',
        'name': 'Apex Precision Soldering',
        'ownerName': 'Kavita Rao',
        'specialty': 'Logic Board Micro-Soldering Specialist',
        'category': ['Smartphone', 'Laptop', 'Wearable'],
        'distanceKm': 5.1,
        'verified': True,
        'verificationStatus': 'VERIFIED',
        'rating': 4.85,
        'reviewCount': 120,
        'completedRepairs': 140,
        'location': 'Hitec City, Hyderabad',
        'address': 'Cyber Gateway Rd, Madhapur',
        'city': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500081',
        'experienceYears': 7,
        'openingHours': 'Mon–Sat: 10:00 AM – 06:30 PM | Sun: Closed',
        'availability': 'OPEN',
        'description': 'Ultra-precision board-level logic diagnostics, short-circuit rail detection, and high-density IC swaps under stereo optical microscopy.',
        'services': ['Motherboard Diagnostics', 'Micro-soldering', 'Charging Problems', 'NAND Flash Recovery'],
        'specializations': ['Apple', 'Samsung'],
        'hourlyRate': 1100,
        'avatar': 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=500&auto=format&fit=crop&q=80',
        'responseTime': '< 2 hours',
        'phone': '+91 97412 88390',
        'email': 'kavita@apexprecision.in'
    },
    {
        'id': 'rep-pending-volt',
        'name': 'VoltCraft Diagnostics Hub',
        'ownerName': 'Sameer Joshi',
        'specialty': 'Audio, Console & Portable Electronics',
        'category': ['Audio', 'Gaming Devices', 'Wearable'],
        'distanceKm': 4.6,
        'verified': False,
        'verificationStatus': 'PENDING',
        'rating': 0,
        'reviewCount': 0,
        'completedRepairs': 0,
        'location': 'FC Road, Pune',
        'address': 'Fergusson College Road, Deccan Gymkhana',
        'city': 'Pune',
        'state': 'Maharashtra',
        'pincode': '411005',
        'experienceYears': 4,
        'openingHours': 'Mon–Sat: 11:00 AM – 07:00 PM | Sun: Closed',
        'availability': 'OPEN',
        'description': 'New applicant workshop awaiting official ReTrace protocol on-site audit and calibration certificate verification.',
        'services': ['Audio Repair', 'Console Diagnostics', 'Battery Replacement'],
        'specializations': ['Sony', 'Bose', 'Nintendo'],
        'hourlyRate': 750,
        'avatar': 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=500&auto=format&fit=crop&q=80',
        'responseTime': '< 4 hours',
        'phone': '+91 98200 91823',
        'email': 'sameer@voltcraft.io'
    }
]

INITIAL_RESALE_LISTINGS = [
    {
        'id': 'resale-1',
        'productId': 'prod-samsung-58219',
        'productCode': 'RP-SM-58219',
        'productName': 'Samsung Galaxy S23 Ultra (Phantom Black)',
        'brand': 'Samsung',
        'model': 'Galaxy S23 Ultra',
        'condition': 'GOOD',
        'age': '1.4 years',
        'repairCount': 1,
        'verifiedRepairsCount': 1,
        'askingPrice': 47500,
        'originalPrice': 124999,
        'description': 'Flawlessly maintained flagship. Brand new front glass laminated by Volt Precision Labs with complete ReTrace digital passport warranty attached.',
        'accessories': ['Original S-Pen', '65W GaN Charger', 'Spigen Rugged Armor Case'],
        'images': ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80'],
        'sellerId': 'user-avi',
        'sellerName': 'Avi Sharma',
        'status': 'ACTIVE',
        'createdAt': '2026-09-18T10:00:00Z',
        'hasPassport': True,
        'batteryHealth': '91%'
    },
    {
        'id': 'resale-2',
        'productId': 'prod-thinkpad-44102',
        'productCode': 'RP-LN-44102',
        'productName': 'Lenovo ThinkPad T14 Gen 2 (Ryzen 7 PRO / 32GB RAM)',
        'brand': 'Lenovo',
        'model': 'ThinkPad T14 Gen 2',
        'condition': 'FAIR',
        'age': '2.8 years',
        'repairCount': 1,
        'verifiedRepairsCount': 1,
        'askingPrice': 24000,
        'originalPrice': 89000,
        'description': 'Workhorse business laptop with verified keyboard replacement record. Pristine motherboard, upgraded 32GB memory. Includes active ReTrace lifecycle passport.',
        'accessories': ['Original 65W Lenovo USB-C Charger', 'ThinkPad Sleeve'],
        'images': ['https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80'],
        'sellerId': 'user-avi',
        'sellerName': 'Avi Sharma',
        'status': 'ACTIVE',
        'createdAt': '2026-09-22T08:30:00Z',
        'hasPassport': True,
        'batteryHealth': '78%'
    }
]

INITIAL_RECOVERY_PARTNERS = [
    {
        'id': 'rec-greencycle',
        'name': 'GreenCycle Circular Hub',
        'type': 'E_WASTE',
        'typeLabel': 'Responsible E-Waste & Zero-Landfill Smelting',
        'distanceKm': 3.2,
        'verified': True,
        'pickupAvailable': True,
        'rating': 4.95,
        'location': 'Peenya Industrial Area Stage 2, Bengaluru',
        'acceptedCategories': ['Laptops', 'Desktops', 'Smartphones', 'Lithium Batteries', 'Circuit Boards'],
        'description': 'R2v3 Certified responsible recycler with ISO 14001 environmental compliance. Complete chain-of-custody destruction and rare-earth recovery certificate issued for every product.'
    },
    {
        'id': 'rec-ecorenew',
        'name': 'EcoRenew Precious Metals & Rare Earths',
        'type': 'MATERIAL_RECOVERY',
        'typeLabel': 'Precious Metal & Silicon Extraction',
        'distanceKm': 5.8,
        'verified': True,
        'pickupAvailable': True,
        'rating': 4.88,
        'location': 'Electronic City Phase 1, Bengaluru',
        'acceptedCategories': ['Motherboards', 'CPUs', 'Gold Plated Connectors', 'RAM'],
        'description': 'Hydro-metallurgical refining plant recovering 99.4% of gold, silver, copper, and neodymium from dead circuit boards and end-of-life electronics.'
    },
    {
        'id': 'rec-techreclaim',
        'name': 'TechReclaim Harvesting Lab',
        'type': 'PARTS_HARVEST',
        'typeLabel': 'Component Salvage & Circular Second-Life Testing',
        'distanceKm': 4.0,
        'verified': True,
        'pickupAvailable': True,
        'rating': 4.82,
        'location': 'Shivajinagar Circular Yard, Bengaluru',
        'acceptedCategories': ['Broken Laptops', 'Cracked Tablets', 'Obsolete Workstations'],
        'description': 'Harvests viable ICs, power supplies, screen backlights, and storage drives to refurbish devices for non-profits and digital education projects.'
    },
    {
        'id': 'rec-urbanore',
        'name': 'Urban Ore Mineral Recovery',
        'type': 'MATERIAL_RECOVERY',
        'typeLabel': 'Lithium & Cobalt Closed Loop Refiner',
        'distanceKm': 8.5,
        'verified': True,
        'pickupAvailable': False,
        'rating': 4.75,
        'location': 'Bommasandra Industrial Zone, Bengaluru',
        'acceptedCategories': ['Li-Ion Batteries', 'Li-Polymer Pouches', 'Power Banks'],
        'description': 'Zero-emission battery shredding and hydrometallurgical recycling facility extracting battery-grade lithium carbonate and cobalt sulfate.'
    },
    {
        'id': 'rec-cleanearth',
        'name': 'CleanEarth Government Authorized Recycler',
        'type': 'E_WASTE',
        'typeLabel': 'Certified Data Destruction & E-Waste Processing',
        'distanceKm': 6.1,
        'verified': True,
        'pickupAvailable': True,
        'rating': 4.9,
        'location': 'Doddaballapur Green Park, Bengaluru',
        'acceptedCategories': ['Enterprise Servers', 'Laptops', 'Telecom Gear'],
        'description': 'Authorized by the Central Pollution Control Board (CPCB) with NIST 800-88 compliant magnetic degaussing and shredding certificates.'
    }
]

INITIAL_SPARE_PARTS = [
    {
        'id': 'part-1',
        'partNumber': 'DL-FAN-5510',
        'name': 'Dell Inspiron 15 5000 Series CPU/GPU Dual Cooling Fan Assembly',
        'category': 'Cooling & Thermal',
        'compatibleModels': ['Dell Inspiron 15 5000', 'Dell Inspiron 15 5510', 'Dell Vostro 5510'],
        'type': 'ORIGINAL',
        'source': 'Dell Certified Distribution Network',
        'availability': 'IN_STOCK',
        'price': 1850,
        'verified': True,
        'lastUpdated': '2026-09-20',
        'warrantyMonths': 12,
        'image': 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=300&auto=format&fit=crop&q=80'
    },
    {
        'id': 'part-2',
        'partNumber': 'TP-ARCTIC-MX6',
        'name': 'Arctic MX-6 High Performance Thermal Compound (4g)',
        'category': 'Thermal Interface',
        'compatibleModels': ['Universal Laptop & Desktop Heatsinks'],
        'type': 'ORIGINAL',
        'source': 'Authorized Thermal Solutions Partner',
        'availability': 'IN_STOCK',
        'price': 650,
        'verified': True,
        'lastUpdated': '2026-09-22',
        'warrantyMonths': 24,
        'image': 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=300&auto=format&fit=crop&q=80'
    },
    {
        'id': 'part-3',
        'partNumber': 'DL-BAT-54WH',
        'name': 'Dell 3-Cell 54Wh OEM Li-Ion Battery (V6W33 / G91J0)',
        'category': 'Batteries',
        'compatibleModels': ['Dell Inspiron 15 5000', 'Dell Inspiron 14 5410', 'Dell Latitude 3420'],
        'type': 'ORIGINAL',
        'source': 'Dell India Components Supply',
        'availability': 'IN_STOCK',
        'price': 3400,
        'verified': True,
        'lastUpdated': '2026-09-21',
        'warrantyMonths': 12,
        'image': 'https://images.unsplash.com/photo-1619725002198-6a689b72f41d?w=300&auto=format&fit=crop&q=80'
    },
    {
        'id': 'part-4',
        'partNumber': 'AP-BAT-IP13P',
        'name': 'Apple iPhone 13 Pro 3095mAh High-Density Battery Cell',
        'category': 'Batteries',
        'compatibleModels': ['Apple iPhone 13 Pro'],
        'type': 'ORIGINAL',
        'source': 'Apple Independent Repair Network',
        'availability': 'IN_STOCK',
        'price': 4900,
        'verified': True,
        'lastUpdated': '2026-09-18',
        'warrantyMonths': 6
    },
    {
        'id': 'part-5',
        'partNumber': 'SM-DISP-S23U',
        'name': 'Samsung Dynamic AMOLED 2X Display Module with Frame',
        'category': 'Displays',
        'compatibleModels': ['Samsung Galaxy S23 Ultra'],
        'type': 'ORIGINAL',
        'source': 'Samsung Authorized Parts Hub',
        'availability': 'LOW_STOCK',
        'price': 18500,
        'verified': True,
        'lastUpdated': '2026-09-15',
        'warrantyMonths': 6
    },
    {
        'id': 'part-6',
        'partNumber': 'LN-KB-T14G2',
        'name': 'ThinkPad T14 Gen 2 Backlit Ergonomic Keyboard (US Layout)',
        'category': 'Input Devices',
        'compatibleModels': ['Lenovo ThinkPad T14 Gen 2', 'Lenovo ThinkPad P14s Gen 2'],
        'type': 'ORIGINAL',
        'source': 'Lenovo Enterprise Services',
        'availability': 'IN_STOCK',
        'price': 3100,
        'verified': True,
        'lastUpdated': '2026-09-10',
        'warrantyMonths': 12
    },
    {
        'id': 'part-7',
        'partNumber': 'DL-DISP-15FHD',
        'name': '15.6" Full HD 1920x1080 IPS Anti-Glare 30-Pin Matte Panel',
        'category': 'Displays',
        'compatibleModels': ['Dell Inspiron 15 5000', 'HP Pavilion 15', 'Lenovo IdeaPad 3 15'],
        'type': 'COMPATIBLE',
        'source': 'BOE / LG Display Verified Supplier',
        'availability': 'IN_STOCK',
        'price': 4200,
        'verified': True,
        'lastUpdated': '2026-09-14',
        'warrantyMonths': 12
    },
    {
        'id': 'part-8',
        'partNumber': 'SSD-SAMS-980',
        'name': 'Samsung 980 NVMe M.2 2280 PCIe 3.0 SSD (1TB)',
        'category': 'Storage',
        'compatibleModels': ['Dell Inspiron 15 5000', 'Lenovo ThinkPad T14', 'Universal M.2 NVMe Laptops'],
        'type': 'ORIGINAL',
        'source': 'Samsung Electronics Distributor',
        'availability': 'IN_STOCK',
        'price': 6800,
        'verified': True,
        'lastUpdated': '2026-09-23',
        'warrantyMonths': 60
    },
    {
        'id': 'part-9',
        'partNumber': 'RAM-CRUC-16GB',
        'name': 'Crucial 16GB DDR4 3200MHz SODIMM Laptop Memory Module',
        'category': 'Memory',
        'compatibleModels': ['Dell Inspiron 15 5000', 'Lenovo ThinkPad T14', 'HP Pavilion 15'],
        'type': 'ORIGINAL',
        'source': 'Crucial Official Distributor',
        'availability': 'IN_STOCK',
        'price': 2900,
        'verified': True,
        'lastUpdated': '2026-09-24',
        'warrantyMonths': 120
    },
    {
        'id': 'part-10',
        'partNumber': 'DL-DC-JACK-5500',
        'name': 'Dell Inspiron DC-In Power Charging Harness Jack Cable',
        'category': 'Power & Ports',
        'compatibleModels': ['Dell Inspiron 15 5000', 'Dell Inspiron 15 5593'],
        'type': 'COMPATIBLE',
        'source': 'Verified Aftermarket Tier-1',
        'availability': 'IN_STOCK',
        'price': 550,
        'verified': True,
        'lastUpdated': '2026-09-19',
        'warrantyMonths': 6
    },
    {
        'id': 'part-11',
        'partNumber': 'AP-CAM-13P',
        'name': 'Apple iPhone 13 Pro Triple-Lens Camera System OEM Module',
        'category': 'Cameras',
        'compatibleModels': ['Apple iPhone 13 Pro'],
        'type': 'ORIGINAL',
        'source': 'Certified Salvage & Tested Genuine Harvest',
        'availability': 'LOW_STOCK',
        'price': 8200,
        'verified': True,
        'lastUpdated': '2026-09-17',
        'warrantyMonths': 3
    },
    {
        'id': 'part-12',
        'partNumber': 'USBC-PORT-40PIN',
        'name': 'Type-C USB-PD Charging Port Receptacle SMT 24-Pin',
        'category': 'Connectors',
        'compatibleModels': ['Universal Modern Laptops & Phones'],
        'type': 'COMPATIBLE',
        'source': 'Foxconn / Amphenol Component Line',
        'availability': 'IN_STOCK',
        'price': 220,
        'verified': True,
        'lastUpdated': '2026-09-22',
        'warrantyMonths': 12
    },
    {
        'id': 'part-13',
        'partNumber': 'DL-HNG-SET-5510',
        'name': 'Dell Inspiron 15 Left & Right Steel LCD Hinge Set',
        'category': 'Chassis & Hinges',
        'compatibleModels': ['Dell Inspiron 15 5510', 'Dell Inspiron 15 5000'],
        'type': 'ORIGINAL',
        'source': 'Dell Certified Spares',
        'availability': 'IN_STOCK',
        'price': 1100,
        'verified': True,
        'lastUpdated': '2026-09-16',
        'warrantyMonths': 12
    },
    {
        'id': 'part-14',
        'partNumber': 'TP-WIFI-AX210',
        'name': 'Intel Wi-Fi 6E AX210 M.2 NGFF Wireless Card with Bluetooth 5.3',
        'category': 'Networking',
        'compatibleModels': ['Dell Inspiron 15 5000', 'Lenovo ThinkPad T14', 'Universal M.2 Key-E'],
        'type': 'ORIGINAL',
        'source': 'Intel Authorized Network Distributor',
        'availability': 'IN_STOCK',
        'price': 1750,
        'verified': True,
        'lastUpdated': '2026-09-20',
        'warrantyMonths': 24
    },
    {
        'id': 'part-15',
        'partNumber': 'LN-BAT-T14-50WH',
        'name': 'Lenovo ThinkPad Internal Li-Polymer Battery Pack 50Wh',
        'category': 'Batteries',
        'compatibleModels': ['Lenovo ThinkPad T14 Gen 1/2', 'Lenovo ThinkPad P14s'],
        'type': 'ORIGINAL',
        'source': 'Lenovo OEM Depot',
        'availability': 'PRE_ORDER',
        'price': 4800,
        'verified': True,
        'lastUpdated': '2026-09-12',
        'warrantyMonths': 12
    }
]

INITIAL_REPAIR_REVIEWS = [
    {
        'id': 'rev-1',
        'repairerId': 'rep-techfix',
        'userId': 'user-avi',
        'userName': 'Avi Sharma',
        'rating': 5,
        'comment': 'Excellent service. They replaced my Dell battery with an authentic OEM part and updated the ReTrace passport immediately.',
        'createdAt': '2025-04-19T10:00:00Z',
        'verifiedRepair': True
    },
    {
        'id': 'rev-2',
        'repairerId': 'rep-techfix',
        'userId': 'user-rahul',
        'userName': 'Rahul Verma',
        'rating': 5,
        'comment': 'Deep cleaned my heatsink and reapplied thermal paste. Laptop runs 15 degrees cooler now. Highly recommended!',
        'createdAt': '2026-02-13T11:20:00Z',
        'verifiedRepair': True
    },
    {
        'id': 'rev-3',
        'repairerId': 'rep-devicecare',
        'userId': 'user-priya',
        'userName': 'Priya Mehta',
        'rating': 4,
        'comment': 'Very professional screen replacement for my Samsung. The display quality is perfect, just took a bit longer than expected.',
        'createdAt': '2024-11-12T14:30:00Z',
        'verifiedRepair': True
    }
]
